name: ci

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  rust_version: 1.53.0

jobs:

  check:
    strategy:
      matrix:
        include:
        - os: macos-11.0
        - os: windows-2019
          features: cmake-build,libz-static,curl-static
          rdkafka-sys-features: cmake-build,libz-static,curl-static
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.rust_version }}
        default: true
    - run: cargo build --all-targets --verbose --features "${{ matrix.features }}"
    - run: cd rdkafka-sys && cargo test --features "${{ matrix.rdkafka-sys-features }}"

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - confluent-version: 5.0.3
          kafka-version: 2.0
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.rust_version }}
        default: true
    - run: sudo apt-get update
    - run: sudo apt-get install -qy valgrind
    - run: ./test_suite.sh
      env:
        CONFLUENT_VERSION: ${{ matrix.confluent-version }}
        KAFKA_VERSION: ${{ matrix.kafka-version }}
        TERM: xterm-256color
