name: ci

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  rust_version: 1.53.0

jobs:

  check:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.rust_version }}
        default: true
    - run: cargo build --all-targets --verbose --features "cmake-build,libz-static,curl-static"
    - run: cd rdkafka-sys && cargo test --features "cmake-build,libz-static,curl-static"
