name: ci

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  rust_version: 1.53.0

jobs:

  check:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-2019
          features: cmake-build,libz-static,curl-static
          rdkafka-sys-features: cmake-build,libz-static,curl-static
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.rust_version }}
        default: true
    - run: cargo build --all-targets --verbose --features "${{ matrix.features }}"
    - run: cd rdkafka-sys && cargo test --features "${{ matrix.rdkafka-sys-features }}"
